/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicDeepAnalysisRouteImport } from './routes/api/public/deep-analysis'
import { Route as ApiPublicGenerateReportRouteImport } from './routes/api/public/generate-report'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDeepAnalysisRoute = ApiPublicDeepAnalysisRouteImport.update({
  id: '/api/public/deep-analysis',
  path: '/api/public/deep-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGenerateReportRoute = ApiPublicGenerateReportRouteImport.update({
  id: '/api/public/generate-report',
  path: '/api/public/generate-report',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/deep-analysis': typeof ApiPublicDeepAnalysisRoute
  '/api/public/generate-report': typeof ApiPublicGenerateReportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/deep-analysis': typeof ApiPublicDeepAnalysisRoute
  '/api/public/generate-report': typeof ApiPublicGenerateReportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/deep-analysis': typeof ApiPublicDeepAnalysisRoute
  '/api/public/generate-report': typeof ApiPublicGenerateReportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/public/deep-analysis' | '/api/public/generate-report'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/deep-analysis' | '/api/public/generate-report'
  id:
    | '__root__'
    | '/'
    | '/api/public/deep-analysis'
    | '/api/public/generate-report'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicDeepAnalysisRoute: typeof ApiPublicDeepAnalysisRoute
  ApiPublicGenerateReportRoute: typeof ApiPublicGenerateReportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/deep-analysis': {
      id: '/api/public/deep-analysis'
      path: '/api/public/deep-analysis'
      fullPath: '/api/public/deep-analysis'
      preLoaderRoute: typeof ApiPublicDeepAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/generate-report': {
      id: '/api/public/generate-report'
      path: '/api/public/generate-report'
      fullPath: '/api/public/generate-report'
      preLoaderRoute: typeof ApiPublicGenerateReportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicDeepAnalysisRoute: ApiPublicDeepAnalysisRoute,
  ApiPublicGenerateReportRoute: ApiPublicGenerateReportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
